services:
  api-1:
    image: nestjs-vehicle-register:latest
    expose:
      - "8080"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/vehicles
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - mongodb

  api-2:
    image: nestjs-vehicle-register:latest
    expose:
      - "8080"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/vehicles
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - mongodb

  api-3:
    image: nestjs-vehicle-register:latest
    expose:
      - "8080"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/vehicles
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "2"
          memory: 2G
    command: mongod --wiredTigerCacheSizeGB 2 --journalCommitInterval 100 --wiredTigerCollectionBlockCompressor snappy

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 2G
    depends_on:
      - api-1
      - api-2
      - api-3
    tmpfs:
      - /var/cache/nginx:size=1024m
