services:
  api-1:
    image: nestjs-vehicle-register:latest
    expose:
      - "8080"
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/vehicles?connection_limit=2&pool_timeout=0
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - postgres
    command: >
      sh -c "npx prisma db push --schema prisma/schema.prisma && node dist/main.js"

  api-2:
    image: nestjs-vehicle-register:latest
    expose:
      - "8080"
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/vehicles?connection_limit=2&pool_timeout=0
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - postgres
      - api-1

  api-3:
    image: nestjs-vehicle-register:latest
    expose:
      - "8080"
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/vehicles?connection_limit=2&pool_timeout=0
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - postgres
      - api-1

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vehicles
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 3G
        reservations:
          cpus: "2"
          memory: 3G
    command:
      - postgres
      - "-c"
      - "shared_buffers=1.5GB"
      - "-c"
      - "wal_buffers=32MB"
      - "-c"
      - "work_mem=32MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "effective_cache_size=3GB"
      - "-c"
      - "max_connections=300"
      - "-c"
      - "synchronous_commit=off"
      - "-c"
      - "wal_compression=on"
      - "-c"
      - "checkpoint_timeout=20min"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "random_page_cost=1.1"
    tmpfs:
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=2G

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "1"
          memory: 1G
    depends_on:
      - api-1
      - api-2
      - api-3
    tmpfs:
      - /var/cache/nginx:size=1024m
