services:
  api-1:
    image: nestjs-vehicle-register:latest
    expose:
      - "8080"
    environment:
      DATABASE_URL: postgresql://admin:admin@pgbouncer:6432/vehicles?pgbouncer=true&connection_limit=10&pool_timeout=0
      DIRECT_DATABASE_URL: postgresql://admin:admin@pgbouncer:6432/vehicles
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - postgres
    command: >
      sh -c "npx prisma db push --schema prisma/schema.prisma && node dist/main.js"

  api-2:
    image: nestjs-vehicle-register:latest
    expose:
      - "8080"
    environment:
      DATABASE_URL: postgresql://admin:admin@pgbouncer:6432/vehicles?pgbouncer=true&connection_limit=10&pool_timeout=0
      DIRECT_DATABASE_URL: postgresql://admin:admin@pgbouncer:6432/vehicles
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - postgres
      - api-1

  api-3:
    image: nestjs-vehicle-register:latest
    expose:
      - "8080"
    environment:
      DATABASE_URL: postgresql://admin:admin@pgbouncer:6432/vehicles?pgbouncer=true&connection_limit=10&pool_timeout=0
      DIRECT_DATABASE_URL: postgresql://admin:admin@pgbouncer:6432/vehicles
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - postgres
      - api-1

  api-4:
    image: nestjs-vehicle-register:latest
    expose:
      - "8080"
    environment:
      DATABASE_URL: postgresql://admin:admin@pgbouncer:6432/vehicles?pgbouncer=true&connection_limit=10&pool_timeout=0
      DIRECT_DATABASE_URL: postgresql://admin:admin@pgbouncer:6432/vehicles
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - postgres
      - api-1

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vehicles
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 3G
        reservations:
          cpus: "1.5"
          memory: 3G
    command:
      - postgres
      - "-c"
      - "shared_buffers=1.5GB"
      - "-c"
      - "wal_buffers=32MB"
      - "-c"
      - "work_mem=32MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "effective_cache_size=3GB"
      - "-c"
      - "max_connections=600"
      - "-c"
      - "synchronous_commit=off"
      - "-c"
      - "wal_compression=on"
      - "-c"
      - "checkpoint_timeout=20min"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "random_page_cost=1.1"
    tmpfs:
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=2G

  pgbouncer:
    image: bitnami/pgbouncer
    ports:
      - "6432:6432"
    environment:
      - PGBOUNCER_POOL_MODE=transaction
      - PGBOUNCER_MAX_CLIENT_CONN=600
      - PGBOUNCER_DEFAULT_POOL_SIZE=200
      - PGBOUNCER_MIN_POOL_SIZE=20
      - PGBOUNCER_IGNORE_STARTUP_PARAMETERS=extra_float_digits
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT_NUMBER=5432
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=vehicles
      - PGBOUNCER_DATABASE=vehicles
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 0.5G
        reservations:
          cpus: "0.5"
          memory: 0.5G

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 0.5G
        reservations:
          cpus: "0.4"
          memory: 0.5G
    depends_on:
      - api-1
      - api-2
      - api-3
      - api-4
    tmpfs:
      - /var/cache/nginx:size=1024m
