services:
  api-1:
    image: csipkes-gergo-nestjs-vehicle-register:latest
    environment:
      MONGODB_URI: mongodb://localhost:27017/vehicles
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      PORT: 8081
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - mongodb
    network_mode: "host"

  api-2:
    image: csipkes-gergo-nestjs-vehicle-register:latest
    environment:
      MONGODB_URI: mongodb://localhost:27017/vehicles
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      PORT: 8082
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - mongodb
    network_mode: "host"

  api-3:
    image: csipkes-gergo-nestjs-vehicle-register:latest
    environment:
      MONGODB_URI: mongodb://localhost:27017/vehicles
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      PORT: 8083
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - mongodb
    network_mode: "host"

  mongodb:
    image: mongo:latest
    deploy:
      resources:
        limits:
          cpus: "1.7"
          memory: 3G
        reservations:
          cpus: "1.7"
          memory: 3G
    command: mongod --wiredTigerCacheSizeGB 3 --journalCommitInterval 100 --wiredTigerCollectionBlockCompressor snappy
    network_mode: "host"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 2G
        reservations:
          cpus: "0.4"
          memory: 2G
    depends_on:
      - api-1
      - api-2
      - api-3
    tmpfs:
      - /var/cache/nginx:size=1024m
    network_mode: "host"

  redis:
    image: redis:latest
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 1G
        reservations:
          cpus: "0.3"
          memory: 1G
    network_mode: "host"
