services:
  api-1:
    image: nestjs-vehicle-register:latest
    expose:
      - "8080"
    environment:
      DATABASE_URL: postgresql://admin:admin@pgbouncer:6432/vehicles?schema=public&connection_limit=20
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - postgres
    command: >
      sh -c "npx prisma migrate deploy --preview-feature --schema prisma/schema.prisma && node dist/main.js"

  api-2:
    image: nestjs-vehicle-register:latest
    expose:
      - "8080"
    environment:
      DATABASE_URL: postgresql://admin:admin@pgbouncer:6432/vehicles?schema=public&connection_limit=20
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - postgres

  api-3:
    image: nestjs-vehicle-register:latest
    expose:
      - "8080"
    environment:
      DATABASE_URL: postgresql://admin:admin@pgbouncer:6432/vehicles?schema=public&connection_limit=20
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - postgres

  api-4:
    image: nestjs-vehicle-register:latest
    expose:
      - "8080"
    environment:
      DATABASE_URL: postgresql://admin:admin@pgbouncer:6432/vehicles?schema=public&connection_limit=20
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vehicles
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 3G
        reservations:
          cpus: "1.5"
          memory: 3G
    command:
      - postgres
      - "-c"
      - "shared_buffers=1.5GB"
      - "-c"
      - "wal_buffers=32MB"
      - "-c"
      - "work_mem=32MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "effective_cache_size=3GB"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "synchronous_commit=off"
      - "-c"
      - "wal_compression=on"
      - "-c"
      - "checkpoint_timeout=20min"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "random_page_cost=1.1"
    tmpfs:
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=2G

  pgbouncer:
    image: edoburu/pgbouncer
    ports:
      - "6432:6432"
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 500
      DEFAULT_POOL_SIZE: 50
      MIN_POOL_SIZE: 20
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 0.5G
        reservations:
          cpus: "0.1"
          memory: 0.5G

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 0.5G
        reservations:
          cpus: "0.4"
          memory: 0.5G
    depends_on:
      - api-1
      - api-2
      - api-3
      - api-4
    tmpfs:
      - /var/cache/nginx:size=1024m
